### ISSUE TITLE
BUG: getValidMoves generates IndexError

### ISSUE THREAD

**Issue by coolusaHD** [cogsys-tuebingen/ai_competition#6]
## Description
Sometimes the function `getKingsideCastleMoves` get called with `index=35` and with

 `getKingsideCastleMoves ` in `ChessEngine:732`
`if self.board[rc + 1] == "--":` 

it ends in an IndexError

## Error Output:
```
  File "C:\Projekte\chess_ai\student_agents\template.py", line 313, in alphaBetaMin
    validMoves = gs.getValidMoves()
  File "C:\Projekte\chess_ai\ChessEngine.py", line 306, in getValidMoves
    self.getCastleMoves(kingRow, kingCol, moves)
  File "C:\Projekte\chess_ai\ChessEngine.py", line 708, in getCastleMoves
    self.getKingsideCastleMoves(r, c, moves)
  File "C:\Projekte\chess_ai\ChessEngine.py", line 732, in getKingsideCastleMoves
    if self.board[rc + 1] == "--":
IndexError: list index out of range
```

**Comment by toddChavezz** [comment]
do you have a board position to reproduce this? I didn't encounter this myself

**Comment by coolusaHD** [comment]
Maybe you can try it with the following board:

```
'--' '--' '--' '--' '--' '--' 
'--' '--' '--' '--' '--' '--' 
'--' '--' '--' '--' '--' '--' 
'--' '--' '--' '--' '--' '--' 
'--' '--' '--' '--' '--' '--' 
'--' '--' '--' '--' '--' 'wK' 
```

**Comment by toddChavezz** [comment]
yes, this also produces a KeyError. but at a different location:
```
Traceback (most recent call last):
  File "/home/messmer/aatutorium/ai/Games/DianaChessPython/Chess/ChessMain.py", line 683, in <module>
    main(args)
  File "/home/messmer/aatutorium/ai/Games/DianaChessPython/Chess/ChessMain.py", line 312, in main
    animateMove(game_state.moveLog[-1], screen, game_state.board, clock)
  File "/home/messmer/aatutorium/ai/Games/DianaChessPython/Chess/ChessMain.py", line 558, in animateMove
    screen.blit(IMAGES[move.pieceMoved], py.Rect(c * SQ_SIZE, r * SQ_SIZE, SQ_SIZE, SQ_SIZE))
KeyError: '--'
```

**Comment by coolusaHD** [comment]
Okay intressting...
